import "../globals.css";
import React from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <main className="min-h-screen bg-background flex flex-col items-center">
        {children}
      </main>
    </html>
  );
}
